### ISSUE TITLE
AddOns not updated for 4.0.6

### ISSUE THREAD

**Issue by Saur2000** [tekkub/wow-ui-source#1]
As far as I can tell the AddOns directory has not been updated to match what is in 4.0.6. I extracted the latest version of the AddOns folder from the MPQ files myself, and got a 17k lines patch compared to what is in the current wow-ui-source repository...

After taking a closer look at the repository, it seems as if all the changes between 40.3a and 4.0.6 to the AddOns directory were reverted in commit 6415bbe58ce7e5be15c3008152896379db662144. My guess is that this was not intentional.

**Comment by tekkub** [comment]
Indeed, seems the game pulls the addons from disk instead of from the MPQ, and I had the old patch's addons on my disk.

**Comment by kennethreitz** [comment]
Test comment.
